---
title: "Sentiment_Demo"
author: "Patrick Zivkovic"
date: "1 6 2020"
output: html_document
---

```{r setup, include=FALSE}
pacman::p_load(dplyr, data.table, forcats, ggplot2, qdap, tm, udpipe, hunspell, tidytext, parallel, tictoc, tidyr)
nrc = tidytext::get_sentiments(lexicon = "nrc")
text <- fread("1_data_text_cleaned.csv")
```

Lyrics of a sample song (Abba - She's my kind of girl)
```{r}
lyrics <- text[1,3]
lyrics
```

Simple bag of words of the lyrics of the song
```{r}
bag <- tibble(word = bag_o_words(lyrics))
sort(table(bag),decreasing=T)
```

NRC (Word-Emotion Association Lexicon)
```{r}
nrc
```

## Sentiment analysis: 8 basic emotions

Connect the words conveying emotion in the song to the sentiments of the lexicon 
```{r}
emotion_word = tibble(word = bag_o_words(lyrics)) %>% inner_join(nrc, by = "word")
emotion_word
```

Get the relative proportion of the given emotions
```{r}
total_words <- dim(emotion_word)[1]
emotion_word %>% 
  group_by(sentiment)
emotion_word %>% 
  group_by(sentiment) %>% 
  count()
emotion_word %>% 
  group_by(sentiment) %>% 
  count() %>% 
  mutate(n = n/total_words)
```




## Sentiment Analysis: Positive/Negative

```{r}
afinn = tidytext::get_sentiments(lexicon = "afinn")
sentiments = distinct(get_sentiments(lexicon = "bing"))
```

```{r}
emotion_word = tibble(word = bag_o_words(lyrics)) %>% inner_join(afinn, by = "word") %>% left_join(sentiments, by = "word")
emotion_word
```

```{r}
emotion_word[is.na(emotion_word$sentiment), 3] <- "neutral"
emotion_word
```

```{r}
emotion_word_count = emotion_word %>% group_by(sentiment) %>% summarise(n = sum(abs(value)))
emotion_word_count
```

```{r, include=FALSE}
setwd('C:/Users/Patrick Zivkovic/Documents/GitHub/Data-Challenge-Songlyrics')
data <- fread("merged_dataset.csv")
data[1:100,]
```





